project:
  type: website

website:
  title: "Quartoblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: [litera, styles.scss]
    css: styles.scss
    highlight-style: tango

editor: visual

